[matching]
"com.mitchellh.ghostty.ssh" = "󰣀"
"com.mitchellh.ghostty" = ""
"org.mozilla.firefox" = ""
"code" = "󰨞"
"Slack" = "󰒱"
"discord" = "󰙯"
"Spotify" = ""
"thunar" = "󰉋"
"nautilus" = "󰉋"
"mpv" = "󰂍"
"imv" = "󰕓"
"org.telegram.desktop" = ""
